### ISSUE TITLE
MCrypt was DEPRECATED in PHP 7.1.0, and REMOVED in PHP 7.2.0

### ISSUE THREAD

**Issue by halojoy** [alimranahmed/CodeIgnitor-Post#10]
I can not install.
Because I run PHP 7.4.4.
And MCrypt is removed.
The message is: 
 The Encrypt library requires the Mcrypt extension.

**Comment by alimranahmed** [comment]
Hi, 

Thanks for reporting the issue. 
Unfortunately I don't use Codeigniter as my primary PHP framework anymore and not maintaining this project. 

So, if you think you can fix this issue by yourself, a PR is always welcome.
