### ISSUE TITLE
Edit and Delete Individual Comment, forgot Password (Login) and Send Email Feature

### ISSUE THREAD

**Issue by Darwin03** [alimranahmed/CodeIgnitor-Post#5]
Hi,

Thanks for the CodeIgnitor-Post! It's very interesting...

PLEASE, can the functions/features of "Edit and Delete" individual comment in post be added to the block, based on users and permission??? The blog only have "Edit and Delete" for Post only... Also can the sending feature option be added in contact us of the blog???

EXCUSE ME, I know I asked to much but if can't, I will understand! Can "Forgot password be added to login and can a "Monitor" function/feature for comment/post be added to the blog before publish??? When admin approve comment, then it can be published!

PLEASE, I hope I can get a help with that!!!

THANK YOU!!!

Best Regards,
Darwin.

**Comment by alimranahmed** [comment]
Thanks, this is not a full featured blog. It was for learning purpose, uploaded it if it can help any beginner. Huge work need to be done to make it a full featured blog site.
Besides, I have another repo which is a full featured blog site that has been made using [Laravel 5.7](https://github.com/alimranahmed/LaraBlog)
